<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Copyright>Copyright © Brain Station 23 PLC</Copyright>
    <Company>Brain Station 23</Company>
    <Authors>Sakib Hasan</Authors>
    <RepositoryType>Git</RepositoryType>
    <OutputPath>$(SolutionDir)\Presentation\Nop.Web\Plugins\Misc.FaqManager</OutputPath>
    <OutDir>$(OutputPath)</OutDir>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Admin\Views\Configure.cshtml" />
    <None Remove="Admin\Views\FaqGroups.cshtml" />
    <None Remove="Admin\Views\FaqGroupCreate.cshtml" />
    <None Remove="Admin\Views\FaqGroupEdit.cshtml" />
    <None Remove="Admin\Views\_CreateOrUpdate.FaqGroup.cshtml" />
    <None Remove="Admin\Views\FaqItemCreate.cshtml" />
    <None Remove="Admin\Views\FaqItemEdit.cshtml" />
    <None Remove="Admin\Views\_CreateOrUpdate.FaqItem.cshtml" />
    <None Remove="Admin\Views\_ViewImports.cshtml" />
    <None Remove="Admin\Views\_ViewStart.cshtml" />
    <None Remove="logo.png" />
    <None Remove="plugin.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Admin\Views\Configure.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Admin\Views\FaqGroups.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Admin\Views\FaqGroupCreate.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Admin\Views\FaqGroupEdit.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Admin\Views\_CreateOrUpdate.FaqGroup.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Admin\Views\FaqItemCreate.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Admin\Views\FaqItemEdit.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Admin\Views\_CreateOrUpdate.FaqItem.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Admin\Views\_ViewImports.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Admin\Views\_ViewStart.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="plugin.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)\Presentation\Nop.Web\Nop.Web.csproj" />
    <ProjectReference Include="..\..\Presentation\Nop.Web.Framework\Nop.Web.Framework.csproj" />
    <ClearPluginAssemblies Include="$(SolutionDir)\Build\ClearPluginAssemblies.proj" />
  </ItemGroup>

  <!-- This target execute after "Build" target -->
  <Target Name="NopTarget" AfterTargets="Build">
    <!-- Delete unnecessary libraries from plugins path -->
    <MSBuild Projects="@(ClearPluginAssemblies)" Properties="PluginPath=$(OutDir)" Targets="NopClear" />
  </Target>

</Project>